FROM golang:1.17.2 AS build

WORKDIR /
COPY . .
ENV CGO_ENABLED=0
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct
RUN GOOS=linux go build -installsuffix cgo -o httpserver main.go

FROM scratch
COPY --from=build /httpserver /httpserver
EXPOSE 80
WORKDIR /
ENTRYPOINT ["./httpserver"]